name = "cloudflare-worker-boilerplate"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]



[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "miseriaeentries"
id = "todo_replace_with_kv_id"
preview_id = "todo_replace_with_preview_id"
